<?php

/**
 * @file
 * Primary module hooks for wwsauth module.
 */

use Drupal\user\UserInterface;
use Drupal\user\Entity\Role;

/**
 * Implements hook_openid_connect_userinfo_save().
 */
function wwsauth_openid_connect_userinfo_save(UserInterface $account, array $context) {
  if ($context['plugin_id'] !== 'wwsumich') {
    return;
  }
  $config = Drupal::config('openid_connect.client.wwsumich');
  $roles = $config->get('settings')['roles'] ?? FALSE;
  if(!$roles || !is_array($roles)) {
    return;
  }

  ## Get all roles
  $all_roles = [];
  foreach (Role::loadMultiple() as $r) {
    $all_roles[$r->label()] = $r->id();
  }
  foreach ($roles as $role) {
    $account->removeRole($all_roles[$role]);
  }

  if ( isset($context['userinfo']['edumember_ismemberof']) && is_array($context['userinfo']['edumember_ismemberof'])) {
    foreach ($context['userinfo']['edumember_ismemberof'] as $role) {
      if (in_array($role, $roles)) {
        $account->addRole($all_roles[$role]);
      }
    }
  }

}
